spring.application.name=forohub
spring.datasource.url=jdbc:postgresql://localhost:5432/forohub_db
spring.datasource.username=postgres
spring.datasource.password=kkck0210

spring.jpa.show-sql=true

spring.jackson.default-property-inclusion=non_null

spring.security.user.name=user
spring.security.user.password=123456